pipeline {
    agent any
    environment {
        PATH = "/opt/maven/latest/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml' // Changed the path to include subdirectories
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
           
        stage('Complete') {
            steps {
                echo 'Job complete'
            }
        }
          
    }
}
